(function () {
  const api = window.QuartSysApi;
  if (!api) return;

  const main = document.querySelector("main");
  const status = document.createElement("div");
  status.className = "text-xs text-slate-400 px-6 py-2";
  if (main) main.prepend(status);

  function setStatus(text, isError) {
    status.textContent = text || "";
    status.className = `text-xs px-6 py-2 ${isError ? "text-red-400" : "text-slate-400"}`;
  }

  function inferConditions(prompt) {
    const p = (prompt || "").toLowerCase();
    const cond = [];
    if (p.includes("ma") || p.includes("均线") || p.includes("trend")) cond.push("ma60");
    if (p.includes("volume") || p.includes("成交量") || p.includes("spike")) cond.push("volume");
    if (p.includes("rsi") || p.includes("candlestick") || p.includes("yin") || p.includes("yang")) cond.push("yin_yang");
    return cond.length ? cond : ["ma60"];
  }

  async function loadParams() {
    try {
      const params = await api.get("/params");
      const selects = document.querySelectorAll("select");
      const ranges = document.querySelectorAll("input[type='range']");
      const holdInput = Array.from(document.querySelectorAll("input[type='text']")).find((i) =>
        /bars/i.test(i.value || "")
      );

      if (selects[0] && Array.isArray(params.enabled_conditions) && params.enabled_conditions.includes("yin_yang")) {
        selects[0].value = "RSI Crossover";
      } else if (selects[0]) {
        selects[0].value = "Price < BB Lower";
      }

      if (holdInput) holdInput.value = `${Math.max(5, Number(params.ma_trend_days || 12))} Bars`;
      if (ranges[0]) ranges[0].value = String(Math.min(30, Math.max(5, Number(params.slope_threshold || 12))));
      if (ranges[1]) ranges[1].value = String(Math.min(15, Math.max(1, Number(params.ma_proximity_threshold || 4) * 10)));
      setStatus("策略参数已从后端加载", false);
    } catch (e) {
      setStatus(e.message || "策略参数加载失败", true);
    }
  }

  function renderCodePreview(prompt, cond) {
    const pre = document.querySelector("pre");
    if (!pre) return;
    pre.innerHTML =
      `import <span class="text-white">pandas</span> as <span class="text-white">pd</span>\n` +
      `# Generated by Strategy AI Engine\n` +
      `# Prompt: ${prompt.replace(/</g, "&lt;")}\n` +
      `enabled_conditions = ${JSON.stringify(cond)}\n` +
      `match_mode = "all"\n` +
      `print("Strategy synced to backend params")`;
  }

  async function syncStrategy(prompt, triggerScreen) {
    const cond = inferConditions(prompt);
    const ranges = document.querySelectorAll("input[type='range']");
    const slope = Number(ranges[0] ? ranges[0].value : 15);
    const proximity = Number(ranges[1] ? ranges[1].value : 4) / 10;

    await api.post("/params", {
      ma_days: 60,
      ma_proximity_threshold: proximity,
      ma_trend_days: 30,
      volume_check_days: 30,
      volume_spike_ratio: 2.0,
      post_spike_days_count: 5,
      yin_yang_check_days: 20,
      ma_short_days: 20,
      ma_long_days: 60,
      slope_threshold: slope,
      enabled_conditions: cond,
      match_mode: "all"
    });

    renderCodePreview(prompt, cond);
    setStatus(`参数已同步：${cond.join(", ")}`, false);

    if (triggerScreen) {
      await api.post("/screen", {});
      setStatus(`已触发筛选任务：${cond.join(", ")}`, false);
    }
  }

  function bindActions() {
    const promptInput = document.querySelector("textarea");
    const genBtn = Array.from(document.querySelectorAll("button")).find((b) =>
      /Generate Strategy/i.test(b.textContent || "")
    );
    const sendRoundBtn = Array.from(document.querySelectorAll("button")).find((b) =>
      b.querySelector(".material-symbols-outlined") && /auto_awesome/i.test(b.innerHTML)
    );
    const backtestBtns = Array.from(document.querySelectorAll("button")).filter((b) =>
      /Backtest/i.test(b.textContent || "")
    );

    if (genBtn && !genBtn.dataset.bound) {
      genBtn.dataset.bound = "1";
      genBtn.addEventListener("click", async function () {
        const prompt = (promptInput && promptInput.value ? promptInput.value : "").trim();
        if (!prompt) {
          setStatus("请输入策略描述后再生成", true);
          return;
        }
        try {
          await syncStrategy(prompt, true);
        } catch (e) {
          setStatus(e.message || "策略生成失败", true);
        }
      });
    }

    if (sendRoundBtn && !sendRoundBtn.dataset.bound) {
      sendRoundBtn.dataset.bound = "1";
      sendRoundBtn.addEventListener("click", async function () {
        const prompt = (promptInput && promptInput.value ? promptInput.value : "").trim();
        if (!prompt) {
          setStatus("请输入策略描述", true);
          return;
        }
        try {
          await syncStrategy(prompt, false);
        } catch (e) {
          setStatus(e.message || "参数同步失败", true);
        }
      });
    }

    backtestBtns.forEach((btn) => {
      if (btn.dataset.bound) return;
      btn.dataset.bound = "1";
      btn.addEventListener("click", function () {
        window.location.href = "../backtesting_agent_analysis/code.html";
      });
    });
  }

  loadParams();
  bindActions();
})();

