export const MAIN_TEXT_ZH_MAP: Array<[RegExp, string]> = [
  [/Market Intelligence/gi, "市场情报"],
  [/Global Risk Dashboard/gi, "全局风险看板"],
  [/Top Gainers/gi, "涨幅榜"],
  [/Industry Leaders/gi, "行业龙头"],
  [/View All Markets/gi, "查看全部市场"],
  [/Holding/gi, "持仓"],
  [/Watch/gi, "自选"],
  [/YIELD RANKING/gi, "收益排行"],
  [/Yield Ranking/gi, "收益排行"],
  [/Live Simulation Status/gi, "实时模拟状态"],
  [/Agent Fleet Management/gi, "智能体集群管理"],
  [/Pause All/gi, "全部暂停"],
  [/Restart All/gi, "全部重启"],
  [/View All Rankings/gi, "查看全部排行"],
  [/Load More Agents/gi, "加载更多智能体"],
  [/AI Diagnostic/gi, "AI 诊断"],
  [/Optimize Weights/gi, "优化权重"],
  [/Backtesting/gi, "回测分析"],
  [/Risk Monitor/gi, "风险监控"],
  [/Trading/gi, "交易终端"],
  [/Settings/gi, "系统设置"],
  [/Dashboard/gi, "行情数据"],
  [/Screener/gi, "选股器"],
  [/Strategy AI/gi, "AI 策略"],
  [/AI Insights/gi, "AI洞察"],
  [/No data/gi, "暂无数据"],
  [/No active positions/gi, "暂无持仓"],
  [/Open/gi, "开盘"],
  [/Close/gi, "收盘"],
  [/BUY\/UP/gi, "买入/看涨"],
  [/SELL\/DOWN/gi, "卖出/看跌"],
  [/Profit\/Loss/gi, "盈亏"],
  [/Available Funds/gi, "可用资金"],
  [/Position Value/gi, "持仓市值"],
  [/System Active/gi, "系统运行中"],
  [/External Relays/gi, "外部通道"],
  [/Switch to Register/gi, "切换到注册"],
  [/Forgot Password\?/gi, "忘记密码？"],
  [/AUTHENTICATE TERMINAL/gi, "登录系统"],
  [/REGISTER TERMINAL/gi, "注册账号"],
  [/RESET PASSWORD/gi, "重置密码"],
  [/System Access/gi, "系统入口"],
  [
    /Initialize your terminal to access the quantitative core\./gi,
    "初始化终端以访问量化核心。",
  ],
  [/Terminal ID \(Email\/Phone\)/gi, "终端账号（邮箱/手机号）"],
  [/Access Key/gi, "访问密钥"],
  [/Security Audit/gi, "安全审计"],
  [/Privacy Protocals/gi, "隐私协议"],
  [/Current Plan/gi, "当前套餐"],
  [/Pay \$/gi, "支付 $"],
  [/API Config/gi, "API 配置"],
  [/Generate Strategy/gi, "生成策略"],
  [/Refreshed at/gi, "刷新时间"],
  [/Next update in 15m/gi, "下次更新 15 分钟后"],
  [/BULLISH/gi, "看涨"],
  [/BEARISH/gi, "看跌"],
  [/NEUTRAL/gi, "中性"],
  [/LOW RISK/gi, "低风险"],
  [/MID RISK/gi, "中风险"],
  [/HIGH RISK/gi, "高风险"],

  // Strategy AI
  [/Strategy AI Engine/gi, "AI 策略引擎"],
  [
    /Describe your logic in plain English to generate high-performance Python code\./gi,
    "用自然语言描述你的交易逻辑，生成高性能 Python 策略代码。",
  ],
  [/Generate Strategy/gi, "生成策略"],
  [/Logic Parameters/gi, "逻辑参数"],
  [/SYNCED TO AI/gi, "已与 AI 同步"],
  [/Buy Condition/gi, "买入条件"],
  [/Holding Period/gi, "持仓周期"],
  [/Profit Target/gi, "止盈目标"],
  [/Stop Loss/gi, "止损"],
  [/Saved Agent Strategies/gi, "已保存策略"],
  [/Ready to Live/gi, "可实盘"],
  [/Testing/gi, "测试中"],
  [/Backtest/gi, "回测"],
  [/Combine Agent/gi, "组合智能体"],
  [/Trend Following/gi, "趋势跟随"],
  [/Arbitrage/gi, "套利"],
  [/Scalping/gi, "剥头皮"],
  [/Explain your trading logic\.\.\./gi, "请输入你的交易逻辑..."],

  // Backtesting
  [/Agent Multi-Performance/gi, "智能体多策略表现"],
  [/Backtest duration: 90 Days/gi, "回测区间：90 天"],
  [/Add Benchmark/gi, "添加基准"],
  [/View All Rankings/gi, "查看全部排行"],
  [/Execution Status/gi, "执行状态"],
  [/Strategy Type/gi, "策略类型"],
  [/Agent Identity/gi, "智能体标识"],
  [/Drawdown/gi, "回撤"],
  [/Actions/gi, "操作"],
  [/Load More Agents/gi, "加载更多智能体"],
  [/Running/gi, "运行中"],
  [/Stopped/gi, "已停止"],

  // Risk monitor
  [/Risk Trend Analysis/gi, "风险趋势分析"],
  [/Capital Flow \(Top Indices\)/gi, "资金流向（核心指数）"],
  [/Major Risk Event Timeline/gi, "重大风险事件时间线"],
  [/Global Risk Score/gi, "全局风险评分"],
  [/Beta Exposure/gi, "Beta 暴露"],
  [/HEARTBEAT_STABLE/gi, "系统心跳稳定"],
  [/AI Strategy Assessment/gi, "AI 策略评估"],
  [/Systemic Flow Diagram/gi, "系统性流向图"],
  [/Source/gi, "来源"],
  [/Aggregate/gi, "聚合"],
  [/Destination/gi, "去向"],
  [/Volatility/gi, "波动"],
  [/Systemic Risk/gi, "系统性风险"],
  [/Critical/gi, "高危"],
  [/Liquidity/gi, "流动性"],
  [/Commodities/gi, "商品"],
  [/Bullish/gi, "看多"],

  // Trading
  [/Order Book/gi, "订单簿"],
  [/Open Orders/gi, "当前委托"],
  [/Positions/gi, "持仓"],
  [/Market Depth/gi, "市场深度"],
  [/Place Order/gi, "下单"],
  [/Buy/gi, "买入"],
  [/Sell/gi, "卖出"],

  // Settings
  [/Profile & Billing/gi, "账户与订阅"],
  [/Preferences/gi, "偏好设置"],
  [/Security/gi, "安全设置"],
  [/Subscription Tiers/gi, "订阅方案"],
  [/Current Plan/gi, "当前计划"],
  [/Pay \$49 Now/gi, "立即支付 $49"],
  [/Pay \$199 Now/gi, "立即支付 $199"],
  [/Basic Access/gi, "基础版"],
  [/High Frequency/gi, "高频版"],
  [/Institutional/gi, "旗舰版"],
  [/System Tray Activity/gi, "系统托盘运行"],
  [/Trade Alerts/gi, "交易提醒"],
  [/Interface Theme/gi, "界面主题"],
  [/Keep OS active in background\./gi, "保持系统后台运行。"],
  [/Toggle between light and dark modes\./gi, "在浅色与深色模式间切换。"],
  [/Push notifications for order fills\./gi, "成交后推送通知。"],
];

export function toZhContent(html: string) {
  const iconPlaceholders: string[] = [];
  const protectedHtml = html.replace(
    /<span([^>]*class=["'][^"']*material-symbols-outlined[^"']*["'][^>]*)>([\s\S]*?)<\/span>/gi,
    (_full, attrs, inner) => {
      const key = `__QS_ICON_${iconPlaceholders.length}__`;
      iconPlaceholders.push(`<span${attrs}>${inner}</span>`);
      return key;
    },
  );

  const translated = MAIN_TEXT_ZH_MAP.reduce(
    (acc, [pattern, next]) => acc.replace(pattern, next),
    protectedHtml,
  );

  return translated.replace(
    /__QS_ICON_(\d+)__/g,
    (_m, idx) => iconPlaceholders[Number(idx)] || _m,
  );
}
